package org.openpixi.pixi.physics.grid;

import org.openpixi.pixi.physics.particles.IParticle;

public interface InterpolatorAlgorithm {

	/**
	 * This method computes the current on the grid generated by the movement of the particles.
	 *
	 * @param p     Particle instance
	 * @param g     Reference to the grid
	 */
	void interpolateToGrid(IParticle p, Grid g);

	/**
	 * This method interpolates the charge density of a single particle to the charge density on the grid.
	 *
	 * @param p     Particle instance
	 * @param g     Reference to the grid
	 */
	void interpolateChargedensity(IParticle p, Grid g);

	/**
	 * This method interpolates fields on the grid to the particle positions.
	 *
	 * @param p     Particle instance
	 * @param g     Reference to the grid
	 */
	void interpolateToParticle(IParticle p, Grid g);

}